### ISSUE TITLE
Undo bd901ef once unstable patches xz

### ISSUE THREAD

**Issue by IldenH** [IldenH/nixos-system#9]
bd901ef temporarily fixes xz by changing to staging-next nixpkgs. Has to build with --impure temporarily.

**Comment by LilleAila** [comment]
`xz` has now been downgraded in nixpkgs: https://search.nixos.org/packages?channel=unstable&show=xz&from=0&size=50&sort=relevance&type=packages&query=xz
The temporary fix can now be removed.
